version: '3'

services:
  node-app:
    image: node:latest
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: npm start

  vue-app:
    image: node:latest
    working_dir: /usr/src/vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./path/to/your/vue/app:/usr/src/vue-app
    command: npm run serve

  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: your_username
      # MONGO_INITDB_ROOT_PASSWORD: your_password
      MONGO_INITDB_DATABASE: alunosServidores
